version: "3"

services:

  php-fpm-container:
    image: my-php-fpm:7.3.8
    ports:
      - "9000:9000"
    volumes: 
      - ./www:/var/www/html
      - ./etc/php:/usr/local/etc
      - ./log/php:/var/log/php

  nginx:
    image: nginx
    depends_on:
      - "php-fpm-container"
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./etc/nginx:/etc/nginx
      - ./log/nginx:/var/log/nginx
